openapi: 3.0.0
info:
    title: 'Passenger score'
    version: '1.0'

paths:
    /setScore:
        post:
            description: 'Add a new passenger score'
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/Score'
            responses:
                '201':
                    description: 'Added'
                    content:
                      application/json:
                        schema:
                            $ref: '#/components/schemas/Score'
                '400':
                    description: 'Bad request'
                '404':
                    description: 'Passenger not found'
                    
    /getScore:
        get:
            description: 'Get passenger score'
            parameters:
                - in: query
                  name: id
                  required: true
                  schema:
                    type: "integer"
            responses:
                '200':
                    description: 'Ok'
                    content:
                      application/json:
                        schema:
                            $ref: '#/components/schemas/Score'
                '400':
                    description: 'Bad request'
                '404':
                    description: 'Passenger not found'

components:
    schemas:
        Score:
            type: object
            additionalProperties: false
            properties:
                passenger_id:
                    type: "integer"
                    format: "int64"
                score:
                    type: "integer"
                    format: "int64"
                    minimum: 1
                    maximum: 10
                badPerson:
                    type: "boolean"
                    default: false
                datetime:
                    type: "string"
            required:
              - passenger_id
              - score
              - badPerson
              - datetime