openapi: "3.0.0"
info:
  title: "Family account"
  description: "General payment method in the group"
  version: 0.0.1

paths:
  /create_family_account:
    get:
      responses:
        "201":
          description: "created"
        "400":
          description: "account has already been created"
          
  /delete_family_account:
    get:
      responses:
        "200":
          description: "deleted"
        "403":
          description: "u don't have the permission"
                
  /add_member:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDataValid"
      responses:
        "201":
          description: "user has been added"
        "400":
          description: "invalid data"
          
  /delete_member:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDataValid"
      responses:
        "200":
          description: "user has been deleted"
        "400":
          description: "user not in the group"
        "403":
          description: "u don't have the permission"
          content:
            application/json:
              schema:
                type: string
